# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 18:14
from __future__ import unicode_literals

import artist.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('email_token', models.CharField(blank=True, max_length=32, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=artist.models.artist_directory_path)),
                ('caption', models.CharField(max_length=50)),
                ('artist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('facebook_url', models.URLField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('budget_from', models.IntegerField(default=0)),
                ('budget_to', models.IntegerField(default=0)),
                ('artist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
    ]
