# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 18:14
from __future__ import unicode_literals

import cafe.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('email_token', models.CharField(blank=True, max_length=32, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=cafe.models.cafe_directory_path)),
                ('caption', models.CharField(max_length=50)),
                ('cafe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='CafeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('gigs_per_week', models.IntegerField(default=0)),
                ('facebook_url', models.URLField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('cafe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteArtistToCafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_amount', models.IntegerField(default=0)),
                ('q_time', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteCafeToArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_amount', models.IntegerField(default=0)),
                ('q_time', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('counter_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.QuoteArtistToCafe')),
                ('q_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe')),
                ('q_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='quoteartisttocafe',
            name='counter_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.QuoteCafeToArtist'),
        ),
        migrations.AddField(
            model_name='quoteartisttocafe',
            name='q_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='quoteartisttocafe',
            name='q_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe'),
        ),
    ]
