# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecafetoartist',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quotecafetoartist',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotecafetoartist',
            name='uid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='quotecafetoartist',
            name='counter_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.QuoteCafeToArtist'),
        ),
    ]
