# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20180617_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteartisttocafe',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_for_artist', to='cafe.QuoteCafeToArtist'),
        ),
        migrations.AddField(
            model_name='quotecafetoartist',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotecafetoartist',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_for_cafe', to='cafe.QuoteCafeToArtist'),
        ),
        migrations.AlterField(
            model_name='quotecafetoartist',
            name='counter_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.QuoteArtistToCafe'),
        ),
    ]
