# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('cafe', '0003_auto_20180617_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('uid', models.UUIDField(null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_opportunity', to='artist.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='quoteartisttocafe',
            name='counter_to',
        ),
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='counter_to',
        ),
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='uid',
        ),
        migrations.AlterField(
            model_name='quoteartisttocafe',
            name='q_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='artists',
            field=models.ManyToManyField(through='cafe.QuoteArtistToCafe', to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe'),
        ),
    ]
