# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20180617_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotecafetoartist',
            name='q_from',
        ),
        migrations.AddField(
            model_name='quotecafetoartist',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Opportunity'),
        ),
    ]
