# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20180617_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
